version: "3.7"
services:

  db:
    image: "postgres:14.5"
    container_name: "postgres"
    restart: always

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: world_data_etl
  
  etl:
      build:
        context: ./etl
      container_name: "etl"
      depends_on:
        - db
  
  streamlit:
    build:
      context: ./streamlit_app
    container_name: "streamlit"
    ports:
      - "8501:8501"
    depends_on:
      - db
      - etl

   

